import pandas as pd

data = {'all purpose flour': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'baking soda': {'cup': 1, 'grams': 227, 'ounces': 8},
        'sugar': {'cup': 1, 'grams': 198, 'ounces': 7},
        'almond flour': {'cup': 1, 'grams': 86, 'ounces': 3},
        'applesauce': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'almonds (sliced)': {'cup': 1, 'grams': 86, 'ounces': 3},
        'almonds (whole)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'amaranth flour': {'cup': 1, 'grams': 103, 'ounces': 3.625},
        'apples (peeled, sliced)': {'cup': 1, 'grams': 113, 'ounces': 4},
        'apricots (dried, diced)': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'bread flour': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'baking powder': {'cup': 1, 'grams': 192, 'ounces': 6.98},
        'bananas': {'cup': 1, 'grams': 227, 'ounces': 8},
        'barley flour': {'cup': 1, 'grams': 85, 'ounces': 3},
        'bell peppers': {'cup': 1, 'grams': 142, 'ounces': 5},
        'blueberries': {'cup': 1, 'grams': 170, 'ounces': 6},
        'bread crumbs (dried)': {'cup': 1, 'grams': 112, 'ounces': 4},
        'bread crumbs (fresh)': {'cup': 1, 'grams': 84, 'ounces': 3},
        'brown rice (cooked)': {'cup': 1, 'grams': 170, 'ounces': 6},
        'brown rice flour': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'buckwheat flour': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'bulgur': {'cup': 1, 'grams': 152, 'ounces': 5.375},
        'butter': {'cup': 1, 'grams': 226, 'ounces': 8},
        'buttermilk': {'cup': 1, 'grams': 227, 'ounces': 8},
        'caraway seeds': {'cup': 1, 'grams': 144, 'ounces': 5},
        'fennel': {'cup': 1, 'grams': 144, 'ounces': 5},
        'carrots (diced)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'carrots (grated)': {'cup': 1, 'grams': 99, 'ounces': 3.5},
        'cashews (chopped)': {'cup': 1, 'grams': 113, 'ounces': 4},
        'cashews (whole)': {'cup': 1, 'grams': 113, 'ounces': 4},
        'celery': {'cup': 1, 'grams': 142, 'ounces': 5},
        'feta cheese': {'cup': 1, 'grams': 114, 'ounces': 4},
        'shredded cheese': {'cup': 1, 'grams': 113, 'ounces': 4},
        'parmesan': {'cup': 1, 'grams': 100, 'ounces': 3.5},
        'ricotta': {'cup': 1, 'grams': 227, 'ounces': 8},
        'cherries (candied)': {'cup': 1, 'grams': 200, 'ounces': 7},
        'cherries (dired)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'cherries (frozen)': {'cup': 1, 'grams': 113, 'ounces': 4},
        'chickpea flour': {'cup': 1, 'grams': 113, 'ounces': 4},
        'chives': {'cup': 1, 'grams': 1.5, 'ounces': 42},
        'chocolate (chopped)': {'cup': 1, 'grams': 170, 'ounces': 6},
        'chocolate chips': {'cup': 1, 'grams': 170, 'ounces': 6},
        'cocoa powder': {'cup': 1, 'grams': 84, 'ounces': 3},
        'coconut (shredded)': {'cup': 1, 'grams': 85, 'ounces': 3},
        'coconut (flakes)': {'cup': 1, 'grams': 2.125, 'ounces': 60},
        'coconut flour': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'coconut oil': {'cup': 1, 'grams': 226, 'ounces': 8},
        'confectioners sugar': {'cup': 1, 'grams': 113.5, 'ounces': 4},
        'cookie crumbs': {'cup': 1, 'grams': 3, 'ounces': 85},
        'popcorn': {'cup': 1, 'grams': 5, 'ounces': 0.188},
        'corn syrup': {'cup': 1, 'grams': 312, 'ounces': 11},
        'cornmeal': {'cup': 1, 'grams': 138, 'ounces': 5.5},
        'cornstarch': {'cup': 1, 'grams': 112, 'ounces': 4},
        'cracked wheat': {'cup': 1, 'grams': 149, 'ounces': 5.25},
        'cranberries (dried)': {'cup': 1, 'grams': 114, 'ounces': 4},
        'cranberries': {'cup': 1, 'grams': 99, 'ounces': 3.5},
        'cream (heavy. light, or half&half)': {'cup': 1, 'grams': 227, 'ounces': 8},
        'cream cheese': {'cup': 1, 'grams': 227, 'ounces': 8},
        'currants': {'cup': 1, 'grams': 142, 'ounces': 5},
        'dates (chopped)': {'cup': 1, 'grams': 149, 'ounces': 5.25},
        'demerara sugar': {'cup': 1, 'grams': 220, 'ounces': 7.75},
        'buttermilk powder': {'cup': 1, 'grams': 200, 'ounces': 7},
        'powdered milk': {'cup': 1, 'grams': 5, 'ounces': 140},
        'nonfat milk powder': {'cup': 1, 'grams': 3, 'ounces': 84},
        'potato flakes': {'cup': 1, 'grams': 86, 'ounces': 3},
        'whole milk powder': {'cup': 1, 'grams': 100, 'ounces': 3.5},
        'durum flour': {'cup': 1, 'grams': 124, 'ounces': 4.375},
        'espresso powder': {'cup': 1, 'grams': 112, 'ounces': 4},
        'fig dried': {'cup': 1, 'grams': 149, 'ounces': 5.25},
        'flax meal': {'cup': 1, 'grams': 100, 'ounces': 3.5},
        'flaxseed': {'cup': 1, 'grams': 140, 'ounces': 5},
        'garlic (minced)': {'cup': 1, 'grams': 224, 'ounces': 8},
        'garlic (peeled and sliced)': {'cup': 1, 'grams': 149, 'ounces': 5.25},
        'ginger': {'cup': 1, 'grams': 228, 'ounces': 8},
        'gluten free all-purpose flour': {'cup': 1, 'grams': 156, 'ounces': 5.5},
        'graham crackers (crushed)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'grape nuts': {'cup': 1, 'grams': 114, 'ounces': 4},
        'hazelnut flour': {'cup': 1, 'grams': 89, 'ounces': 3.125},
        'hazelnut spread': {'cup': 1, 'grams': 320, 'ounces': 11.25},
        'hazelnuts (whole)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'honey': {'cup': 1, 'grams': 336, 'ounces': 12},
        'jam': {'cup': 1, 'grams': 340, 'ounces': 12},
        'kefir': {'cup': 1, 'grams': 250, 'ounces': 8},
        'preserves': {'cup': 1, 'grams': 340, 'ounces': 12},
        'lard': {'cup': 1, 'grams': 226, 'ounces': 8},
        'leeks (diced)': {'cup': 1, 'grams': 92, 'ounces': 3.25},
        'macadamia nuts': {'cup': 1, 'grams': 149, 'ounces': 5.25},
        'malt syrup': {'cup': 1, 'grams': 344, 'ounces': 12},
        'maple syrup': {'cup': 1, 'grams': 312, 'ounces': 11},
        'marshmallow fluff': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'marshmallows (mini)': {'cup': 1, 'grams': 43, 'ounces': 1.5},
        'mashed potatoes': {'cup': 1, 'grams': 213, 'ounces': 7.5},
        'mayonnaise': {'cup': 1, 'grams': 226, 'ounces': 8},
        'meringue powder': {'cup': 1, 'grams': 172, 'ounces': 6},
        'evaporated milk': {'cup': 1, 'grams': 226, 'ounces': 8},
        'milk': {'cup': 1, 'grams': 227, 'ounces': 8},
        'millet': {'cup': 1, 'grams': 206, 'ounces': 7.25},
        'mini chocolate chips': {'cup': 1, 'grams': 177, 'ounces': 6.25},
        'molasses': {'cup': 1, 'grams': 340, 'ounces': 12},
        'mushrooms (sliced)': {'cup': 1, 'grams': 78, 'ounces': 2.75},
        'oat bran': {'cup': 1, 'grams': 106, 'ounces': 2.75},
        'oat flour': {'cup': 1, 'grams': 92, 'ounces': 3.25},
        'oats (rolled)': {'cup': 1, 'grams': 99, 'ounces': 3.5},
        'olive oil': {'cup': 1, 'grams': 200, 'ounces': 7},
        'olives (sliced)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'onions (diced)': {'cup': 1, 'grams': 142, 'ounces': 5},
        'pastry flour': {'cup': 1, 'grams':106, 'ounces': 3.75},
        'peaches (diced)': {'cup': 1, 'grams': 170, 'ounces': 6},
        'peanut butter': {'cup': 1, 'grams': 270, 'ounces': 9.5},
        'peanuts': {'cup': 1, 'grams': 142, 'ounces': 5},
        'pears (diced)': {'cup': 1, 'grams': 163, 'ounces': 5.75},
        'pecans (diced)': {'cup': 1, 'grams': 114, 'ounces': 4},
        'pine nuts': {'cup': 1, 'grams': 142, 'ounces': 5},
        'pineapple (diced)': {'cup': 1, 'grams': 170, 'ounces': 6},
        'pistachio': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'poppy seeds': {'cup': 1, 'grams': 144, 'ounces': 5},
        'potato flour': {'cup': 1, 'grams': 184, 'ounces': 6.5},
        'pumpernickel flour': {'cup': 1, 'grams': 106, 'ounces': 3.75},
        'pumpkin (canned)': {'cup': 1, 'grams': 227, 'ounces': 8},
        'quick cooking oats': {'cup': 1, 'grams': 89, 'ounces': 3.125},
        'quinoa (cooked)': {'cup': 1, 'grams': 184, 'ounces': 6.5},
        'quinoa flour': {'cup': 1, 'grams': 110, 'ounces': 3.875},
        'rasins': {'cup': 1, 'grams':149 , 'ounces': 5.25},
        'raspberries': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'rice (long grain, dry)': {'cup': 1, 'grams': 198, 'ounces': 7},
        'rice flour': {'cup': 1, 'grams': 142, 'ounces': 5},
        'rice crispies': {'cup': 1, 'grams': 28, 'ounces': 1},
        'rye flour': {'cup': 1, 'grams': 103, 'ounces': 3.625},
        'table salt': {'cup': 1, 'grams': 288, 'ounces': 10},
        'scallions (sliced)': {'cup': 1, 'grams': 64, 'ounces': 2.25},
        'self-rising flour': {'cup': 1, 'grams': 113, 'ounces': 4},
        'semolina flour': {'cup': 1, 'grams': 163, 'ounces': 5.75},
        'sesame seeds': {'cup': 1, 'grams': 142, 'ounces': 5},
        'shallots (sliced)': {'cup': 1, 'grams': 156, 'ounces': 5.5},
        'sorghum flour': {'cup': 1, 'grams': 138, 'ounces': 4.825},
        'sour cream': {'cup': 1, 'grams': 227, 'ounces': 8},
        'soy flour': {'cup': 1, 'grams': 140, 'ounces': 5},
        'sprouted wheat flour': {'cup': 1, 'grams': 113, 'ounces': 4},
        'steel cut oats (raw)': {'cup': 1, 'grams': 198, 'ounces': 7},
        'steel cut oats (cooked)': {'cup': 1, 'grams': 255, 'ounces': 9},
        'strawberries (sliced)': {'cup': 1, 'grams': 167, 'ounces': 5.825},
        'granulated sugar': {'cup': 1, 'grams': 198, 'ounces': 7},
        'Splenda': {'cup': 1, 'grams': 25, 'ounces': 0.825},
        'sunflower seeds': {'cup': 1, 'grams': 140, 'ounces': 5},
        'sweetened condensed milk': {'cup': 1, 'grams': 312, 'ounces': 11},
        'tahini paste': {'cup': 1, 'grams': 256, 'ounces': 9},
        'tapioca flour': {'cup': 1, 'grams': 113, 'ounces': 4},
        'teff flour': {'cup': 1, 'grams': 135, 'ounces': 4.75},
        'toffee chunks': {'cup': 1, 'grams': 156, 'ounces': 5.5},
        'turbinado sugar': {'cup': 1, 'grams': 180, 'ounces': 6.375},
        'unbleached cake flour': {'cup': 1, 'grams': 120, 'ounces': 4.25},
        'vanilla extract': {'cup': 1, 'grams': 224, 'ounces': 8},
        'vegetable oil': {'cup': 1, 'grams': 198, 'ounces': 7},
        'vegetable shortening': {'cup': 1, 'grams': 184, 'ounces': 6.5},
        'walnuts (chopped)': {'cup': 1, 'grams': 113, 'ounces': 4},
        'walnuts (whole)': {'cup': 1, 'grams': 128, 'ounces': 4.5},
        'water': {'cup': 1, 'grams': 227, 'ounces': 8},
        'wheat bran': {'cup': 1, 'grams': 64, 'ounces': 2.25},
        'wheat germ': {'cup': 1, 'grams': 112, 'ounces': 4},
        'white chocolate chips': {'cup': 1, 'grams': 170, 'ounces': 6},
        'white rye flour': {'cup': 1, 'grams': 106, 'ounces': 3.75},
        'whole wheat flour': {'cup': 1, 'grams': 113, 'ounces': 4},
        'instant yeast': {'cup': 1, 'grams': 149, 'ounces': 5.325},
        'yogurt': {'cup': 1, 'grams': 227, 'ounces': 8},
        'ghee': {'cup': 1, 'grams': 220.69, 'ounces': 7.78},
        'temperature': {'cup': 1, 'grams': 1, 'ounces': 1},
        'brown sugar': {'cup': 1, 'grams': 200, 'ounces': 7.1}}